### ISSUE TITLE
Unable to login via default username/password

### ISSUE THREAD

**Issue by tkosin** [Azure/kubeflow-aks#21]
Hi,

I'm new to AKS and Kubeflow and trying to deploy Kubeflow on AKS using your guideline at https://azure.github.io/kubeflow-aks/main/docs/deployment-options/custom-password-tls/.

<img width="866" alt="image" src="https://github.com/Azure/kubeflow-aks/assets/32434679/0363e5d9-ff6c-4523-b206-15c6fa1bf777">

Dex still returns an invalid username or password. I'm sure I used the default username and password without changing it.

Please help me.

Thank you.

**Comment by seenu433** [comment]
@tkosin - there is no default password. you need to set one as mentioned in the step here https://azure.github.io/kubeflow-aks/main/docs/deployment-options/custom-password-tls/#install-kubeflow-with-tls-and-unique-password

**Comment by mosabami** [comment]
closing this issue with the comment above
