### ISSUE TITLE
Deploying Kubeflow on Azure is not possible

### ISSUE THREAD

**Issue by ChristianSqrt4** [Azure/kubeflow-aks#23]
The GitHub-Repository https://github.com/Azure/kubeflow-aks/ uses the submodule https://github.com/Azure/AKS-Construction/tree/813928a843acd53833286b51d16d7fc6e59ebd6a which is 6 months old. There, the kuberenetes version 1.24.9 is required, see https://github.com/Azure/AKS-Construction/blob/813928a843acd53833286b51d16d7fc6e59ebd6a/bicep/main.bicep#L835. On Azure this kuberenetes version is unsupported. The oldest kubernetes version which is supported is 1.25.6.

Errorlog:
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/62ed105d-8213-450b-b6a4-a6ddb768f348/resourceGroups/kubeflow/providers/Microsoft.Resources/deployments/main","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/62ed105d-8213-450b-b6a4-a6ddb768f348/resourceGroups/kubeflow/providers/Microsoft.Resources/deployments/aksconstruction","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/62ed105d-8213-450b-b6a4-a6ddb768f348/resourceGroups/kubeflow/providers/Microsoft.Resources/deployments/aksconstruction","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","target":"/subscriptions/62ed105d-8213-450b-b6a4-a6ddb768f348/resourceGroups/kubeflow/providers/Microsoft.Resources/deployments/aksconstruction","message":"{\r\n  \"code\": \"AgentPoolK8sVersionNotSupported\",\r\n  \"details\": null,\r\n  \"message\": \"**Version 1.24.9 is not supported in this region**. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list\",\r\n  \"subcode\": \"\"\r\n}"}]}]}]}}

**Comment by mosabami** [comment]
thanks for your issue @ChristianSqrt4 . working on it

**Comment by Raghad-Khaled** [comment]
I have the same issue is there is any solution?

**Comment by mosabami** [comment]
closed with #38
