### ISSUE TITLE
Update Documentation to Reference Latest Release Branch (v1.8-branch)

### ISSUE THREAD

**Issue by MGTheTrain** [Azure/kubeflow-aks#40]
Hi there

---

Issue: 
- ![image](https://github.com/Azure/kubeflow-aks/assets/75074306/5a01dc54-614f-444e-9734-14481a8301af)

Hardware Specs: 
- ubuntu-latest runner
 
![image](https://github.com/Azure/kubeflow-aks/assets/75074306/0d44a5bd-9c31-41d6-b97f-c0420c95ac2e)

Steps to reproduce:

```sh
...
git clone --recurse-submodules https://github.com/Azure/kubeflow-aks.git
cd kubeflow-aks/manifests/
git checkout v1.7-branch
cd ..
cp -a deployments/vanilla manifests/vanilla
cd manifests  
while ! kustomize build vanilla | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
```

Outcome:

![image](https://github.com/Azure/kubeflow-aks/assets/75074306/b1ee4fd0-645e-4d30-a465-70b6c1cded72)

---
FIx: Update documentation (https://azure.github.io/kubeflow-aks/main/docs/deployment-options/vanilla-installation/) pointing to latest release branch (`git checkout v1.8-branch`  ).

Outcome after fix:

![image](https://github.com/Azure/kubeflow-aks/assets/75074306/47217e5c-c943-4a6e-b33b-4a9f9cebfc58)
![image](https://github.com/Azure/kubeflow-aks/assets/75074306/dd7f3ce4-85c7-461a-b42a-7d7fdeb38f67)

**Comment by AdminTurnedDevOps** [comment]
Confirmed this. Ran into the issue for the weekend and utilizing the v1.8 branch fixes this.

**Comment by MGTheTrain** [comment]
Hi AdminTurnedDevOps,

Thank you for confirming that the v1.8 branch resolves the issue you encountered over the weekend.  Your input is appreciated. 
Given the details shared and our hopes for future updates, I'll close the GitHub issue.


Best regards,

MGTheTrain
